# Generated by Django 5.2.8 on 2025-11-19 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên chương trình')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('discount_percentage', models.PositiveIntegerField(help_text='Nhập 20 = giảm 20%', verbose_name='% giảm giá')),
                ('start_time', models.DateTimeField(verbose_name='Thời gian bắt đầu')),
                ('end_time', models.DateTimeField(verbose_name='Thời gian kết thúc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Flash Sale',
                'verbose_name_plural': 'Flash Sale',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='FlashSaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.PositiveIntegerField(verbose_name='Giá gốc')),
                ('sale_price', models.PositiveIntegerField(verbose_name='Giá sale')),
                ('quantity_limit', models.PositiveIntegerField(default=0, help_text='0 = không giới hạn', verbose_name='Số lượng giới hạn')),
                ('sold_quantity', models.PositiveIntegerField(default=0, verbose_name='Đã bán')),
                ('flash_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.flashsale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productmodel')),
            ],
            options={
                'verbose_name': 'Sản phẩm Flash Sale',
                'verbose_name_plural': 'Sản phẩm Flash Sale',
                'unique_together': {('flash_sale', 'product')},
            },
        ),
        migrations.AddField(
            model_name='flashsale',
            name='products',
            field=models.ManyToManyField(through='promotions.FlashSaleProduct', to='catalog.productmodel', verbose_name='Sản phẩm'),
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã voucher')),
                ('name', models.CharField(max_length=200, verbose_name='Tên chương trình')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('discount_type', models.CharField(choices=[('percentage', 'Giảm theo %'), ('fixed', 'Giảm cố định'), ('free_ship', 'Miễn phí vận chuyển')], max_length=20, verbose_name='Loại giảm giá')),
                ('discount_value', models.PositiveIntegerField(help_text='Với % thì nhập 10 = 10%, với cố định thì nhập số tiền VND', verbose_name='Giá trị giảm (% hoặc VND)')),
                ('max_discount', models.PositiveIntegerField(default=0, help_text='Chỉ áp dụng cho giảm theo %. 0 = không giới hạn', verbose_name='Giảm tối đa (VND)')),
                ('min_order_value', models.PositiveIntegerField(default=0, verbose_name='Giá trị đơn hàng tối thiểu (VND)')),
                ('total_quantity', models.PositiveIntegerField(default=0, help_text='0 = không giới hạn', verbose_name='Tổng số lượng')),
                ('used_quantity', models.PositiveIntegerField(default=0, verbose_name='Đã sử dụng')),
                ('usage_limit_per_user', models.PositiveIntegerField(default=1, help_text='0 = không giới hạn', verbose_name='Giới hạn sử dụng mỗi user')),
                ('start_date', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateTimeField(verbose_name='Ngày kết thúc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('is_public', models.BooleanField(default=True, help_text='Voucher công khai sẽ hiển thị cho tất cả user', verbose_name='Công khai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text='Để trống = áp dụng cho tất cả', to='catalog.category', verbose_name='Áp dụng cho danh mục')),
                ('applicable_products', models.ManyToManyField(blank=True, help_text='Để trống = áp dụng cho tất cả', to='catalog.productmodel', verbose_name='Áp dụng cho sản phẩm')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Voucher',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.PositiveIntegerField(verbose_name='Số tiền được giảm')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian sử dụng')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='promotions.voucher')),
            ],
            options={
                'verbose_name': 'Lịch sử sử dụng voucher',
                'verbose_name_plural': 'Lịch sử sử dụng voucher',
                'ordering': ['-used_at'],
            },
        ),
    ]
