# Generated by Django 5.2.8 on 2025-11-19 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Tên ngân hàng')),
                ('bank_code', models.CharField(max_length=20, verbose_name='Mã ngân hàng')),
                ('account_number', models.CharField(max_length=50, verbose_name='Số tài khoản')),
                ('account_holder', models.CharField(max_length=100, verbose_name='Chủ tài khoản')),
                ('branch', models.CharField(blank=True, max_length=100, verbose_name='Chi nhánh')),
                ('qr_code', models.ImageField(blank=True, upload_to='bank_qr/', verbose_name='Mã QR')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Tài khoản ngân hàng',
                'verbose_name_plural': 'Tài khoản ngân hàng',
                'ordering': ['display_order', 'bank_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên gateway')),
                ('display_name', models.CharField(max_length=100, verbose_name='Tên hiển thị')),
                ('logo', models.ImageField(blank=True, upload_to='payment_gateways/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=False, verbose_name='Đang hoạt động')),
                ('config', models.JSONField(default=dict, verbose_name='Cấu hình')),
                ('fixed_fee', models.PositiveIntegerField(default=0, verbose_name='Phí cố định (VND)')),
                ('percentage_fee', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Phí % (2.5 = 2.5%)')),
            ],
            options={
                'verbose_name': 'Cấu hình cổng thanh toán',
                'verbose_name_plural': 'Cấu hình cổng thanh toán',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng (COD)'), ('bank', 'Chuyển khoản ngân hàng'), ('momo', 'Ví MoMo'), ('vnpay', 'VNPay'), ('zalopay', 'ZaloPay')], max_length=20, verbose_name='Phương thức thanh toán')),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('failed', 'Thất bại'), ('refunded', 'Đã hoàn tiền'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('amount', models.PositiveIntegerField(verbose_name='Số tiền (VND)')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Mã giao dịch')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='Phản hồi từ gateway')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày thanh toán')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.ordermodel')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'ordering': ['-created_at'],
            },
        ),
    ]
