# Generated by Django 5.2.8 on 2025-11-21 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='orderlinemodel',
            name='line_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderlinemodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productmodel'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.shippingaddress'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderlinemodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.ordermodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('new', 'Mới'), ('wait', 'Chờ Thanh toán'), ('paid', 'Trả'), ('ship', 'Giao Hàng'), ('done', 'Hoàn Thành'), ('cancel', 'Đã Hủy')], default='new', max_length=10),
        ),
    ]
