# Generated by Django 5.2.8 on 2025-11-19 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254, verbose_name='Email người nhận')),
                ('subject', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('body', models.TextField(verbose_name='Nội dung')),
                ('status', models.CharField(choices=[('pending', 'Chờ gửi'), ('sent', 'Đã gửi'), ('failed', 'Thất bại')], default='pending', max_length=10, verbose_name='Trạng thái')),
                ('error_message', models.TextField(blank=True, verbose_name='Lỗi')),
                ('template_name', models.CharField(blank=True, max_length=100)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch sử email',
                'verbose_name_plural': 'Lịch sử email',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_order_updates', models.BooleanField(default=True, verbose_name='Email cập nhật đơn hàng')),
                ('email_promotions', models.BooleanField(default=True, verbose_name='Email khuyến mãi')),
                ('email_flash_sales', models.BooleanField(default=True, verbose_name='Email flash sale')),
                ('app_order_updates', models.BooleanField(default=True, verbose_name='Thông báo đơn hàng')),
                ('app_promotions', models.BooleanField(default=True, verbose_name='Thông báo khuyến mãi')),
                ('app_flash_sales', models.BooleanField(default=True, verbose_name='Thông báo flash sale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cài đặt thông báo',
                'verbose_name_plural': 'Cài đặt thông báo',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order_confirmed', 'Đơn hàng đã xác nhận'), ('order_shipped', 'Đơn hàng đang giao'), ('order_delivered', 'Đơn hàng đã giao'), ('order_cancelled', 'Đơn hàng đã hủy'), ('payment_success', 'Thanh toán thành công'), ('payment_failed', 'Thanh toán thất bại'), ('low_stock', 'Sản phẩm sắp hết hàng'), ('promotion', 'Khuyến mãi'), ('flash_sale', 'Flash Sale'), ('system', 'Thông báo hệ thống')], max_length=30)),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Đường dẫn')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu bổ sung')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian đọc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
